### ISSUE TITLE
Error on replicating simple pcb

### ISSUE THREAD

**Issue by BrMisha** [MitjaNemec/ReplicateLayout#51]
Hello!
I  got an error in a very simple project. https://drive.google.com/file/d/1UIkyYWt1ip5zRBHbbS3mtmTruTmwN5OM/view?usp=sharing

`04-21 22:59:50 com_github_MitjaNemec_ReplicateLayout.action_replicate_layout 272:Fatal error when running Replicate layout plugin
Traceback (most recent call last):
  File "/home/misha/.local/share/kicad/7.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/action_replicate_layout.py", line 219, in on_ok
    self.replicator.replicate_layout(self.src_anchor_fp, self.src_anchor_fp.sheet_id[0:level + 1],
  File "/home/misha/.local/share/kicad/7.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/replicate_layout.py", line 283, in replicate_layout
    self.replicate_tracks()
  File "/home/misha/.local/share/kicad/7.0/3rdparty/plugins/com_github_MitjaNemec_ReplicateLayout/replicate_layout.py", line 949, in replicate_tracks
    new_track.SetNetCode(to_net_code)
AttributeError: 'BOARD_ITEM' object has no attribute 'SetNetCode'`

**Comment by MitjaNemec** [comment]
I am going to assume you closed this issue accidentally. I'll track this under #52
